apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 8080
    targetPort: 15672
    nodePort: 32000
    name: "management"
  - port: 5672
    targetPort: 5672
    nodePort: 31672
    name: "connection"
